# Generated by Django 5.2 on 2025-05-07 21:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="borrower_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loan",
            name="collateral_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="collateral_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="days_late_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loan",
            name="debt_to_income_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="employment_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loan",
            name="income_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loan",
            name="is_secured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_to_value_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="previous_loans_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loan",
            name="previous_loans_repaid",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loan",
            name="purpose_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="times_late_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loanpayment",
            name="auto_payment_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loanpayment",
            name="late_fee_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="loanpayment",
            name="late_notice_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loanpayment",
            name="late_notice_sent_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanpayment",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loanpayment",
            name="reminder_sent_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("personal", "Personal"),
                    ("business", "Business"),
                    ("education", "Education"),
                    ("debt_consolidation", "Debt Consolidation"),
                    ("home_improvement", "Home Improvement"),
                    ("medical", "Medical"),
                    ("car", "Car Purchase"),
                    ("vacation", "Vacation"),
                    ("wedding", "Wedding"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PortfolioAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "total_invested",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "expected_earnings",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "annual_return_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "avg_loan_risk_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=4
                    ),
                ),
                (
                    "risk_adjusted_return",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("loan_count", models.IntegerField(default=0)),
                ("loans_at_risk_count", models.IntegerField(default=0)),
                (
                    "avg_investment_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "largest_investment_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("purpose_distribution", models.JSONField(default=dict)),
                ("risk_distribution", models.JSONField(default=dict)),
                ("term_distribution", models.JSONField(default=dict)),
                (
                    "investor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_analysis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
