# Generated by Django 5.2 on 2025-05-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowerprofile",
            name="employer_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="borrowerprofile",
            name="employment_duration_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="borrowerprofile",
            name="id_document",
            field=models.FileField(blank=True, null=True, upload_to="verification/id/"),
        ),
        migrations.AddField(
            model_name="borrowerprofile",
            name="identity_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="borrowerprofile",
            name="income_proof",
            field=models.FileField(
                blank=True, null=True, upload_to="verification/income/"
            ),
        ),
        migrations.AddField(
            model_name="borrowerprofile",
            name="income_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="borrowerprofile",
            name="job_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="borrowerprofile",
            name="verification_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="borrowerprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending Verification"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="not_submitted",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="borrowerprofile",
            name="verification_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
