# Generated by Django 5.2 on 2025-05-08 19:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_borrowerprofile_employer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="balance_after",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="related_entity_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="related_entity_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
